const runeValues = [
  ['El', 11, '+50 To Attack Rating, +1 Light Radius', '+15 Defense, +1 To Light Radius',0],
  ['Eld', 11, '+75% Damage To Undead, +50 Attack Rating Against Undead', '15% Slower Stamina Drain/7% Increased Chance of Blocking(Shields)',0],
  ['Tir', 13, '+2 To Mana After Each Kill', '+2 To Mana After Each Kill',0],
  ['Nef', 13, 'Knockback', '+30 Defense Vs. Missile',0],
  ['Eth', 15, '-25% To Target Defense', 'Regenerate Mana 15%',0],
  ['Ith', 15, '+9 To Maximum Damage', '15% Damage Taken Goes to Mana',0],
  ['Tal', 17, '+75 Poison Damage Over 5 Seconds', 'Poison Resist 30%/Poison Resist 35%(Shields)',0],
  ['Ral', 19, 'Adds 5-30 Fire Damage', 'Fire Resist 30%/Fire Resist 35%(Shields)',0],
  ['Ort', 21, 'Adds 1-50 Lightning Damage', 'Lightning Resist 30%/Lightning Resist 35%(Shields)',0],
  ['Thul', 23, 'Adds 3-14 Cold Damage - 3 Second Duration', 'Cold Resist 30%/Cold Resist 35%(Shields)',0],
  ['Amn', 25, '7% Life Stolen Per Hit', 'Attacker Takes Damage of 14',0],
  ['Sol', 27, '+9 To Minimum Damage', 'Damage Reduced By 7',0],
  ['Shael', 29, '20% Increased Attack Speed', '20% Faster Hit Recovery/20% Faster Block Rate(Shields)',0],
  ['Dol', 31, 'Hit Causes Monster To Flee 25%', 'Replenish Life +7',0],
  ['Hel', 0, 'Requirements -20%', 'Requirements -15%',0],
  ['Io', 35, '+10 To Vitality', '+10 To Vitality',0],
  ['Lum', 37, '+10 To Energy', '+10 To Energy',0],
  ['Ko', 39, '+10 To Dexterity', '+10 To Dexterity',0],
  ['Fal', 41, '+10 To Strength', '+10 To Strength',0],
  ['Lem', 43, '75% Extra Gold From Monsters', '50% Extra Gold From Monsters',0],
  ['Pul', 45, '+75% Damage To Demons, +100 Attack Rating Against Demons', '+30% Enhanced Defense',0],
  ['Um', 47, '25% Chance of Open Wounds', 'All Resistances +15(Armor/Helms) +22(Shields)',0],
  ['Mal', 49, 'Prevent Monster Heal', 'Magic Damage Reduced By 7',0],
  ['Ist', 51, '30% Better Chance of Getting Magic Items', '25% Better Chance of Getting Magic Items',0],
  ['Gul', 53, '20% Bonus To Attack Rating', '5% To Maximum Poison Resist',0],
  ['Vex', 55, '7% Mana Stolen Per Hit', '5% To Maximum Fire Resist',0],
  ['Ohm', 57, '+50% Enhanced Damage', '5% To Maximum Cold Resist',0],
  ['Lo', 59, '20% Deadly Strike', '5% To Maximum Lightning Resist',0],
  ['Sur', 61, 'Hit Blinds Target', 'Maximum Mana 5%/+50 To Mana (Shields)',0],
  ['Ber', 63, '20% Chance of Crushing Blow', 'Damage Reduced by 8%',0],
  ['Jah', 65, 'Ignore Targets Defense', 'Increase Maximum Life 5%/+50 Life (Shields)',0],
  ['Cham', 67, 'Freeze Target +3', 'Cannot Be Frozen',0],
  ['Zod', 69, 'Indestructible', 'Indestructible',0]
];

module.exports = {runeValues}; 